version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  hadoop:
    build: ./hadoop
    ports:
      - "9000:9000"
    environment:
      HDFS_NAMENODE_PORT: 9000

  spark:
    build: ./spark
    depends_on:
      - kafka
      - hadoop

  airflow:
    build: ./airflow
    ports:
      - "8080:8080"
    depends_on:
      - spark

  druid:
    build: ./druid
    ports:
      - "8888:8888"
    depends_on:
      - hadoop

  superset:
    build: ./superset
    ports:
      - "8088:8088"
    depends_on:
      - druid

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - spark
      - airflow

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
