global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets: ['spark:4040']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow:8080']
